version: "3.5"
services:
  postgres:
    container_name: postgres
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      # General Config
      POSTGRES_DB: ${POSTGRES_DB:-nuxeo}
      POSTGRES_USER: ${POSTGRES_USER:-nuxeo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nuxeo}
      PGDATA: ${PGDATA}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      # PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
networks:
  postgres:
    external: true
volumes:
  postgres-data:
    driver: local
  pgadmin:
